const { withMainApplication } = require("@expo/config-plugins");

// BrowserStack's real devices route app traffic through a system HTTP
// proxy, and Android has no loopback exclusion list for it — so OkHttp
// (which backs React Native's global `fetch`) sends even `127.0.0.1`
// requests to the proxy. The e2e suite's requests to the in-process map
// server then get a 503 HTML error page (the proxy can't reach the
// device's own loopback). The unix-socket RPC tests are unaffected,
// which is why only the map-server HTTP tests failed on CI while passing
// locally.
//
// Fix: install a ProxySelector that bypasses the proxy for loopback only
// and delegates everything else to the system default. Scoped to
// loopback (rather than disabling proxying outright) so any non-loopback
// traffic still behaves normally. Done as a config plugin because
// `android/` is regenerated by `expo prebuild`.

const IMPORTS = [
  "import com.facebook.react.modules.network.OkHttpClientProvider",
  "import java.net.Proxy",
  "import java.net.ProxySelector",
  "import java.net.URI",
];

const FACTORY_SNIPPET = `    // e2e: bypass any device HTTP proxy for loopback so the in-process
    // map server's requests aren't hijacked (see withLoopbackProxyBypass
    // config plugin).
    val systemProxySelector = ProxySelector.getDefault()
    OkHttpClientProvider.setOkHttpClientFactory {
      OkHttpClientProvider.createClientBuilder(this)
        .proxySelector(object : ProxySelector() {
          override fun select(uri: URI): MutableList<Proxy> {
            val host = uri.host ?: ""
            val isLoopback =
              host == "localhost" || host == "::1" || host.startsWith("127.")
            return if (isLoopback || systemProxySelector == null) {
              mutableListOf(Proxy.NO_PROXY)
            } else {
              systemProxySelector.select(uri)
            }
          }

          override fun connectFailed(
            uri: URI,
            sa: java.net.SocketAddress,
            ioe: java.io.IOException,
          ) {
            systemProxySelector?.connectFailed(uri, sa, ioe)
          }
        })
        .build()
    }
`;

module.exports = function withLoopbackProxyBypass(config) {
  return withMainApplication(config, (cfg) => {
    let src = cfg.modResults.contents;

    if (src.includes("OkHttpClientProvider.setOkHttpClientFactory")) {
      return cfg;
    }

    const importAnchor = "import com.facebook.react.PackageList";
    if (!src.includes(importAnchor)) {
      throw new Error(
        "withLoopbackProxyBypass: could not find import anchor in MainApplication",
      );
    }
    src = src.replace(importAnchor, `${IMPORTS.join("\n")}\n${importAnchor}`);

    const callAnchor = "    loadReactNative(this)";
    if (!src.includes(callAnchor)) {
      throw new Error(
        "withLoopbackProxyBypass: could not find loadReactNative(this) anchor",
      );
    }
    src = src.replace(callAnchor, `${FACTORY_SNIPPET}${callAnchor}`);

    cfg.modResults.contents = src;
    return cfg;
  });
};
