#!/usr/bin/env node
// Generates `src/version.ts` with this module's version + git SHA
// and the bundled-backend dependency map. Re-run on every
// `npm install` (via `prepare`) and `npm pack` / `npm publish`
// (via `prepack`) so the constants reflect what was actually
// built — including the source commit when invoked from a git
// checkout.
//
// `src/version.ts` is gitignored; `npm install` regenerates it
// on first build. Inside an npm tarball no `.git` is present and
// the SHA stays empty, but the published file carries whatever
// SHA the publisher's checkout had at `prepack` time.
//
// A build is marked as an actual npm release when it drops the
// `+git<sha>` suffix, so `comapeo.rn` in Sentry reads as a plain
// semver and the commit moves to the separate `comapeo.rn.sha` tag.

import { readFileSync, writeFileSync, existsSync } from "node:fs";
import { execSync } from "node:child_process";
import { createHash } from "node:crypto";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const root = dirname(dirname(fileURLToPath(import.meta.url)));

const isRelease = process.env.npm_command === "publish";
const pkg = JSON.parse(readFileSync(join(root, "package.json"), "utf8"));
const backendPkg = JSON.parse(
  readFileSync(join(root, "backend", "package.json"), "utf8"),
);

let sha = "";
// `dirty` is the empty string when the working tree is clean,
// or an 8-char hash digest of the working-tree state otherwise.
// Using a hash (rather than a boolean flag) means two different
// uncommitted edits produce two different version labels — so a
// Sentry event from "fixing this bug" can be distinguished from
// "fixing the next bug" without committing in between.
let dirty = "";
if (existsSync(join(root, ".git"))) {
  try {
    sha = execSync("git rev-parse --short=8 HEAD", {
      cwd: root,
      stdio: ["ignore", "pipe", "ignore"],
    })
      .toString()
      .trim();
    // `git diff HEAD` covers staged + unstaged changes to
    // tracked files. `--binary` includes binary diffs verbatim
    // so we don't lose entropy on non-text edits. Untracked
    // files don't contribute (you'd have to `git add` them to
    // matter).
    const diff = execSync("git diff HEAD --binary", {
      cwd: root,
      stdio: ["ignore", "pipe", "ignore"],
      maxBuffer: 256 * 1024 * 1024,
    });
    if (diff.length > 0) {
      dirty = createHash("sha256").update(diff).digest("hex").slice(0, 8);
    }
  } catch {
    // Not a git checkout (shallow tarball etc.) — leave SHA empty.
  }
}

const backendModules = Object.fromEntries(
  Object.entries(backendPkg.dependencies ?? {}).filter(
    ([name]) =>
      // Only ship the comapeo-owned deps as filterable bookkeeping;
      // upstream peers (fastify, tiny-typed-emitter, etc.) bloat the
      // event without being interesting axes for us. Adjust this
      // filter if a non-comapeo dep becomes a pivot point.
      name.startsWith("@comapeo/") || name === "@mapeo/crypto",
  ),
);

// A release keeps only the bare version so `comapeo.rn` reads as "this is a
// published release". Throw if trying to release from a dirty tree, or if no
// git SHA is available (e.g. publishing from a tarball).
if (isRelease) {
  if (dirty) {
    throw new Error(
      `Cannot release from a dirty working tree (dirty=${dirty})`,
    );
  }
  if (!sha) {
    throw new Error(
      "Cannot release from a non-git checkout (no SHA available)",
    );
  }
}
const dirtySuffix = dirty ? `-dirty${dirty}` : "";
const versionLabel = isRelease
  ? pkg.version
  : sha
    ? `${pkg.version}+git${sha}${dirtySuffix}`
    : pkg.version;

const out = `// AUTO-GENERATED by scripts/write-version.mjs — do not edit.
// Regenerated on \`npm install\` and \`npm pack\` via the package's
// \`prepare\` / \`prepack\` scripts. Keep this file gitignored.

/** \`package.json\` version of \`@comapeo/core-react-native\`. */
export const COMAPEO_MODULE_VERSION = ${JSON.stringify(pkg.version)};

/**
 * Short git SHA at build time, or \`""\` for builds outside a git
 * checkout (shallow tarball install).
 */
export const COMAPEO_MODULE_GIT_SHA = ${JSON.stringify(sha)};

/**
 * Hash of the working-tree state at build time.
 * \`""\` for clean builds and npm-installed consumers; an 8-char
 * sha256-prefix digest of \`git diff HEAD --binary\` otherwise.
 * Two distinct sets of uncommitted edits yield two distinct
 * digests, so each in-flight build is uniquely identifiable.
 */
export const COMAPEO_MODULE_DIRTY = ${JSON.stringify(dirty)};

/** Whether this build was produced by the npm release workflow. */
export const COMAPEO_MODULE_IS_RELEASE = ${JSON.stringify(isRelease)};

/**
 * Value of the \`comapeo.rn\` Sentry tag. A release reads as a plain
 * \`<version>\`, so any suffix means the events did NOT come from a
 * published npm release:
 *
 *   1.2.3                     released
 *   1.2.3+git9f2a1c4b         built from a checkout at that commit
 *   1.2.3+git9f2a1c4b-dirty…  …with uncommitted changes
 *
 * The commit is always available separately as \`COMAPEO_MODULE_GIT_SHA\`
 * (the \`comapeo.rn.sha\` tag), so dropping it here loses nothing.
 */
export const COMAPEO_MODULE_VERSION_LABEL = ${JSON.stringify(versionLabel)};

/**
 * Pinned versions of comapeo-owned dependencies bundled into the
 * Node.js backend. The bundle rolls these into a single
 * \`index.mjs\`, so they never appear in the consumer's
 * \`node_modules\` and Sentry's \`ModulesLoader\` integration can't
 * see them. Inject explicitly via \`event.modules\` so they show
 * up on every event from this module's hub.
 */
export const BACKEND_MODULES: Record<string, string> = ${JSON.stringify(backendModules, null, 2)};
`;

writeFileSync(join(root, "src", "version.ts"), out);
console.log(
  `wrote src/version.ts: ${versionLabel}${isRelease ? " [release]" : ""}` +
    `${sha ? ` sha=${sha}` : ""}` +
    ` (backend modules: ${Object.keys(backendModules).length})`,
);
