#!/usr/bin/env node
// Generates `src/version.ts` with this module's version + git SHA
// and the bundled-backend dependency map. Re-run on every
// `npm install` (via `prepare`) and `npm pack` / `npm publish`
// (via `prepack`) so the constants reflect what was actually
// built — including the source commit when invoked from a git
// checkout.
//
// `src/version.ts` is gitignored; `npm install` regenerates it
// on first build. Inside an npm tarball no `.git` is present and
// the SHA stays empty, but the published file carries whatever
// SHA the publisher's checkout had at `prepack` time.

import { readFileSync, writeFileSync, existsSync } from "node:fs";
import { execSync } from "node:child_process";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const root = dirname(dirname(fileURLToPath(import.meta.url)));

const pkg = JSON.parse(readFileSync(join(root, "package.json"), "utf8"));
const backendPkg = JSON.parse(
  readFileSync(join(root, "backend", "package.json"), "utf8"),
);

let sha = "";
let dirty = false;
if (existsSync(join(root, ".git"))) {
  try {
    sha = execSync("git rev-parse --short=8 HEAD", {
      cwd: root,
      stdio: ["ignore", "pipe", "ignore"],
    })
      .toString()
      .trim();
    const status = execSync("git status --porcelain", {
      cwd: root,
      stdio: ["ignore", "pipe", "ignore"],
    })
      .toString()
      .trim();
    dirty = status.length > 0;
  } catch {
    // Not a git checkout (shallow tarball etc.) — leave SHA empty.
  }
}

const backendModules = Object.fromEntries(
  Object.entries(backendPkg.dependencies ?? {}).filter(([name]) =>
    // Only ship the comapeo-owned deps as filterable bookkeeping;
    // upstream peers (fastify, tiny-typed-emitter, etc.) bloat the
    // event without being interesting axes for us. Adjust this
    // filter if a non-comapeo dep becomes a pivot point.
    name.startsWith("@comapeo/") || name === "@mapeo/crypto",
  ),
);

const out = `// AUTO-GENERATED by scripts/write-version.mjs — do not edit.
// Regenerated on \`npm install\` and \`npm pack\` via the package's
// \`prepare\` / \`prepack\` scripts. Keep this file gitignored.

/** \`package.json\` version of \`@comapeo/core-react-native\`. */
export const COMAPEO_MODULE_VERSION = ${JSON.stringify(pkg.version)};

/**
 * Short git SHA at build time, or \`""\` for builds outside a git
 * checkout (shallow tarball install).
 */
export const COMAPEO_MODULE_GIT_SHA = ${JSON.stringify(sha)};

/**
 * Whether the working tree had uncommitted changes at build time.
 * Always \`false\` for clean builds and npm-installed consumers.
 */
export const COMAPEO_MODULE_DIRTY = ${JSON.stringify(dirty)};

/**
 * Composite version label — \`<version>+git<sha>[-dirty]\` when a
 * SHA is available, else just \`<version>\`. Use this as the value
 * of \`event.modules["@comapeo/core-react-native"]\` and the
 * \`comapeo.module.version\` tag so a single dimension covers
 * both release and source identity.
 */
export const COMAPEO_MODULE_VERSION_LABEL = COMAPEO_MODULE_GIT_SHA
  ? \`\${COMAPEO_MODULE_VERSION}+git\${COMAPEO_MODULE_GIT_SHA}\${COMAPEO_MODULE_DIRTY ? "-dirty" : ""}\`
  : COMAPEO_MODULE_VERSION;

/**
 * Pinned versions of comapeo-owned dependencies bundled into the
 * Node.js backend. The bundle rolls these into a single
 * \`index.mjs\`, so they never appear in the consumer's
 * \`node_modules\` and Sentry's \`ModulesLoader\` integration can't
 * see them. Inject explicitly via \`event.modules\` so they show
 * up on every event from this module's hub.
 */
export const BACKEND_MODULES: Record<string, string> = ${JSON.stringify(backendModules, null, 2)};
`;

writeFileSync(join(root, "src", "version.ts"), out);
console.log(
  `wrote src/version.ts: ${pkg.version}${
    sha ? `+git${sha}${dirty ? "-dirty" : ""}` : ""
  } (backend modules: ${Object.keys(backendModules).length})`,
);
