#!/usr/bin/env node
// Generates `src/version.ts` with this module's version + git SHA
// and the bundled-backend dependency map. Re-run on every
// `npm install` (via `prepare`) and `npm pack` / `npm publish`
// (via `prepack`) so the constants reflect what was actually
// built — including the source commit when invoked from a git
// checkout.
//
// `src/version.ts` is gitignored; `npm install` regenerates it
// on first build. Inside an npm tarball no `.git` is present and
// the SHA stays empty, but the published file carries whatever
// SHA the publisher's checkout had at `prepack` time.

import { readFileSync, writeFileSync, existsSync } from "node:fs";
import { execSync } from "node:child_process";
import { createHash } from "node:crypto";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const root = dirname(dirname(fileURLToPath(import.meta.url)));

const pkg = JSON.parse(readFileSync(join(root, "package.json"), "utf8"));
const backendPkg = JSON.parse(
  readFileSync(join(root, "backend", "package.json"), "utf8"),
);

let sha = "";
// `dirty` is the empty string when the working tree is clean,
// or an 8-char hash digest of the working-tree state otherwise.
// Using a hash (rather than a boolean flag) means two different
// uncommitted edits produce two different version labels — so a
// Sentry event from "fixing this bug" can be distinguished from
// "fixing the next bug" without committing in between.
let dirty = "";
if (existsSync(join(root, ".git"))) {
  try {
    sha = execSync("git rev-parse --short=8 HEAD", {
      cwd: root,
      stdio: ["ignore", "pipe", "ignore"],
    })
      .toString()
      .trim();
    // `git diff HEAD` covers staged + unstaged changes to
    // tracked files. `--binary` includes binary diffs verbatim
    // so we don't lose entropy on non-text edits. Untracked
    // files don't contribute (you'd have to `git add` them to
    // matter).
    const diff = execSync("git diff HEAD --binary", {
      cwd: root,
      stdio: ["ignore", "pipe", "ignore"],
      maxBuffer: 256 * 1024 * 1024,
    });
    if (diff.length > 0) {
      dirty = createHash("sha256").update(diff).digest("hex").slice(0, 8);
    }
  } catch {
    // Not a git checkout (shallow tarball etc.) — leave SHA empty.
  }
}

const backendModules = Object.fromEntries(
  Object.entries(backendPkg.dependencies ?? {}).filter(([name]) =>
    // Only ship the comapeo-owned deps as filterable bookkeeping;
    // upstream peers (fastify, tiny-typed-emitter, etc.) bloat the
    // event without being interesting axes for us. Adjust this
    // filter if a non-comapeo dep becomes a pivot point.
    name.startsWith("@comapeo/") || name === "@mapeo/crypto",
  ),
);

const out = `// AUTO-GENERATED by scripts/write-version.mjs — do not edit.
// Regenerated on \`npm install\` and \`npm pack\` via the package's
// \`prepare\` / \`prepack\` scripts. Keep this file gitignored.

/** \`package.json\` version of \`@comapeo/core-react-native\`. */
export const COMAPEO_MODULE_VERSION = ${JSON.stringify(pkg.version)};

/**
 * Short git SHA at build time, or \`""\` for builds outside a git
 * checkout (shallow tarball install).
 */
export const COMAPEO_MODULE_GIT_SHA = ${JSON.stringify(sha)};

/**
 * Hash of the working-tree state at build time.
 * \`""\` for clean builds and npm-installed consumers; an 8-char
 * sha256-prefix digest of \`git diff HEAD --binary\` otherwise.
 * Two distinct sets of uncommitted edits yield two distinct
 * digests, so each in-flight build is uniquely identifiable.
 */
export const COMAPEO_MODULE_DIRTY = ${JSON.stringify(dirty)};

/**
 * Composite version label —
 * \`<version>+git<sha>[-dirty<hash>]\` when a SHA is available,
 * else just \`<version>\`. Use this as the value of
 * \`event.modules["@comapeo/core-react-native"]\` and the
 * \`comapeo.module.version\` tag so a single dimension covers
 * both release and source identity.
 */
export const COMAPEO_MODULE_VERSION_LABEL = COMAPEO_MODULE_GIT_SHA
  ? \`\${COMAPEO_MODULE_VERSION}+git\${COMAPEO_MODULE_GIT_SHA}\${COMAPEO_MODULE_DIRTY ? \`-dirty\${COMAPEO_MODULE_DIRTY}\` : ""}\`
  : COMAPEO_MODULE_VERSION;

/**
 * Pinned versions of comapeo-owned dependencies bundled into the
 * Node.js backend. The bundle rolls these into a single
 * \`index.mjs\`, so they never appear in the consumer's
 * \`node_modules\` and Sentry's \`ModulesLoader\` integration can't
 * see them. Inject explicitly via \`event.modules\` so they show
 * up on every event from this module's hub.
 */
export const BACKEND_MODULES: Record<string, string> = ${JSON.stringify(backendModules, null, 2)};
`;

writeFileSync(join(root, "src", "version.ts"), out);
console.log(
  `wrote src/version.ts: ${pkg.version}${
    sha ? `+git${sha}${dirty ? `-dirty${dirty}` : ""}` : ""
  } (backend modules: ${Object.keys(backendModules).length})`,
);
